version: "3.5"
name: "super-productive-services"
services:
  db:
    image: "postgres"
    restart: always
    container_name: productive-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "productive"
      POSTGRES_PASSWORD: password
    volumes:
      - database-data:/var/lib/postgresql-data/
    ports:
      - 8080:5432

volumes:
  database-data: